name: 'Issue Bot Action'
description: 'Automate your manual tasks with an issue bot'
author: 'imjohnbo'
branding:
  icon: 'at-sign'
  color: 'blue'

inputs:
  token:
    description: |-
      Token used to authenticate with GitHub API. Default is built-in token but a personal access token may be used for organization or user projects.
    required: false
    default: ${{ github.token }}

  title:
    description: |-
      Issue title, e.g. "Daily standup"
    required: true

  body:
    description: |-
      Issue body in Markdown, e.g. # Summary **bolded text**.
    required: false

  labels:
    description: |-
      Comma delimited list of existing issue labels to be applied to new issue, e.g. "bug, ci".
    required: false

  assignees:
    description: |-
      Comma delimited list of issue assignees having write access to repo, e.g. "imjohnbo, nat".
      Assigns new issue to all assignees, or if "rotateAssignees" is set, to the next single assignee whose turn it is.
    required: false

  project-type:
    description: |-
      Project type the "project" number corresponds to, e.g. user, organization, or repository project. 
      Organization and user projects require a GitHub App installation access token, OAuth token, or Personal Access Token.
      Read more here: https://docs.github.com/en/github/managing-your-work-on-github/about-project-boards.
      Defaults to "repository".
    required: false

  project:
    description: |-
      Project number (not ID or name) to add issue to, e.g. 2.
    required: false

  column:
    description: |-
      Project column name to add issue to, e.g. To Do.
      Required if "project" is set.
    required: false

  milestone:
    description: |-
      Milestone number (not ID or name) to add issue to, e.g. 2.
    required: false
  
  pinned:
    description: |-
      Boolean whether to pin this issue and unpin the previous issue matching ALL of the provided "labels".
      Requires "labels".
    default: 'false'
    required: false

  close-previous:
    description: |-
      Boolean whether to close the most recent previous issue matching ALL of the provided "labels".
      Requires "labels".
    default: 'false'
    required: false
    
  linked-comments:
    description: |-
      Boolean whether to write issue comments linking this issue and previous issue matching ALL of the provided "lables",
      e.g. "Previous in series: #345" and "Next in series: #346".
      Requires "labels".
    default: 'false'
    required: false

  linked-comments-new-issue-text:
    description: |-
      Text of the comment on the new issue that links to the previous issue.
      Requires "linked-comments, labels".
    default: 'Previous in series: #{{ previousIssueNumber }}'
    required: false

  linked-comments-previous-issue-text:
    description: |-
      Text of the comment on the previous issue that links to the new issue.
      Requires "linked-comments, labels".
    default: 'Next in series: #{{ newIssueNumber }}'
    required: false

  rotate-assignees:
    description: |-
      Boolean whether to round robin the provided assignees, e.g. for first responder duties.
      Requires "labels", "assignees".
    default: 'false'
    required: false

outputs:
  issue-number:
    description: 'The issue number of the created issue'

  previous-issue-number:
    description: 'The issue number of the previous issue, if available'

runs:
  using: 'node12'
  main: 'dist/index.js'
